import { useEffect } from 'react';
import { PageWrapper } from '@/components/layout/PageWrapper/PageWrapper';
import { SITE_LEGAL, LEGAL_LAST_UPDATED } from '@/utils/constants';
import styles from './LegalPage.module.scss';

const DEFAULT_TITLE = 'SAI ISHANI YOGASHALA — Yoga & Meditation';

export function TermsPage() {
  useEffect(() => {
    document.title = `Terms & Conditions — ${SITE_LEGAL.name}`;
    return () => {
      document.title = DEFAULT_TITLE;
    };
  }, []);

  return (
    <PageWrapper>
      <article className={styles.doc}>
        <header className={styles.hero}>
          <span className={styles.accent} aria-hidden />
          <h1 className={styles.title}>Terms &amp; Conditions</h1>
          <p className={styles.subtitle}>
            Terms of use for {SITE_LEGAL.url} and related services operated by {SITE_LEGAL.name}.
          </p>
          <span className={styles.updated}>Last updated: {LEGAL_LAST_UPDATED}</span>
        </header>

        <div className={styles.prose}>
          <p>
            This document is an electronic record under the Information Technology Act, 2000, and the rules
            made thereunder, as applicable, including amended provisions relating to electronic records in
            other statutes as modified by the Information Technology Act, 2000. This electronic record is
            generated by a computer system and does not require physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with Rule 3 (1) of the Information Technology
            (Intermediaries Guidelines) Rules, 2011, which require publishing the rules and regulations,
            privacy policy, and terms of use for access or usage of the domain name{' '}
            <strong>{SITE_LEGAL.url}</strong> (&quot;Website&quot;), including any related mobile site or
            mobile application (together, the &quot;Platform&quot;).
          </p>
          <p>
            The Platform is owned by <strong>{SITE_LEGAL.name}</strong>, described for these purposes as a
            company incorporated under the Companies Act, 1956, with its registered office at{' '}
            <strong>{SITE_LEGAL.registeredOffice}</strong> (hereinafter &quot;Platform Owner&quot;,
            &quot;we&quot;, &quot;us&quot;, &quot;our&quot;). If your legal structure differs, update this
            description and your registered particulars accordingly.
          </p>
          <p>
            Your use of the Platform and our services and tools is governed by these terms and conditions
            (&quot;Terms of Use&quot;), including applicable policies incorporated by reference. If you
            transact on the Platform, you are also subject to the policies applicable to that transaction. By
            using the Platform, you are contracting with the Platform Owner and these Terms of Use—including
            those policies—form your binding obligations. They relate to your use of our website, goods (if
            any), and services (collectively, &quot;Services&quot;). Any terms you propose that add to or
            conflict with these Terms of Use are rejected and have no effect. We may modify these Terms of Use
            at any time; it is your responsibility to review them periodically.
          </p>
          <p>
            For these Terms of Use, &quot;you&quot;, &quot;your&quot;, or &quot;user&quot; means any natural
            or legal person who agrees to become a user or buyer on the Platform.
          </p>

          <div className={styles.callout}>
            <strong>Important:</strong> Accessing, browsing, or otherwise using the Platform indicates your
            agreement to all the terms and conditions in these Terms of Use. Please read them carefully before
            proceeding.
          </div>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>Use of the Platform and Services</h2>
            <ul className={styles.termsList}>
              <li>
                To access and use the Services, you agree to provide true, accurate, and complete information
                during and after registration, and you are responsible for all activity under your registered
                account.
              </li>
              <li>
                Neither we nor any third party warrants that information or materials on this website or
                through the Services are accurate, complete, or suitable for any particular purpose. Such
                information may contain inaccuracies or errors; we exclude liability for them to the fullest
                extent permitted by law.
              </li>
              <li>
                Your use of the Services and the Platform is at your own risk and discretion; we are not liable
                for your reliance on the Platform except as required by applicable law.
              </li>
              <li>
                The contents of the Platform and the Services are proprietary to us or our licensors. You do
                not acquire any intellectual property rights in those contents, including but not limited to
                design, layout, look, graphics, videos, and course materials, beyond the limited rights
                necessary to use the Services as offered.
              </li>
              <li>
                Unauthorized use of the Platform or Services may result in action under these Terms and/or
                applicable laws.
              </li>
              <li>
                You agree to pay applicable charges for the Services you purchase or subscribe to, as
                displayed at the time of transaction.
              </li>
              <li>
                You agree not to use the Platform or Services for any purpose that is unlawful, illegal, or
                prohibited by these Terms or by applicable Indian or local laws.
              </li>
              <li>
                The Platform may contain links to third-party websites. Those sites are governed by their own
                terms and privacy policies; we provide links for convenience and further information only.
              </li>
              <li>
                When you initiate a transaction to avail Services, you enter into a legally binding contract
                with the Platform Owner for those Services, subject to these Terms.
              </li>
              <li>
                You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (if
                any), and their respective officers, directors, agents, and employees from any claim, demand,
                or actions (including reasonable attorneys&apos; fees) arising from your breach of these
                Terms, our Privacy Policy, or other policies, or your violation of any law or third-party
                rights (including intellectual property rights).
              </li>
              <li>
                To the fullest extent permitted by law, the Platform Owner shall not be liable for any
                indirect, consequential, incidental, special, or punitive damages, including loss of profits,
                revenues, data, or business opportunities, arising from use of or inability to use the
                Services, whether in contract, tort, negligence, or otherwise. Total liability shall not exceed
                the amount you paid for the specific Service giving rise to the claim, or Indian Rupees one
                hundred (₹100), whichever is less.
              </li>
              <li>
                Neither party shall be liable for failure to perform due to events beyond reasonable control
                (force majeure), to the extent permitted by law.
              </li>
              <li>
                These Terms and any dispute or claim arising from or relating to them shall be governed by the
                laws of India.
              </li>
              <li>
                Subject to applicable law, courts in <strong>{SITE_LEGAL.jurisdiction}</strong> shall have
                exclusive jurisdiction over disputes arising out of or in connection with these Terms.
              </li>
              <li>
                All concerns or communications relating to these Terms must be sent using the contact
                information provided on this website.
              </li>
            </ul>
          </section>
        </div>
      </article>
    </PageWrapper>
  );
}
