export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  COURSES: '/courses',
  COURSE_DETAIL: '/courses/:slug',
  MY_LEARNING: '/my-learning',
  PLAYER: '/player/:courseId/:videoId',
  PAYMENT_CALLBACK: '/payments/callback',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_COURSES: '/admin/courses',
  ADMIN_COURSE_NEW: '/admin/courses/new',
  ADMIN_COURSE_EDIT: '/admin/courses/:id/edit',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_VIDEOS: '/admin/videos/:courseId',
  ADMIN_USERS: '/admin/users',
  ADMIN_TRANSACTIONS: '/admin/transactions',
} as const;
